# Hex color format {121212}This is hex color.
# Gradient color format {121212>}GrayWhite{<FFFFFF}

instances: # You can have multiple instances of submission. Use '/neopet open <instance name> <player name>' to open the item submission GUI.
  anniversary: # Instance name.

    point-name: "{B76C1A>}Anniversary Shard{<92B04B}"

    gui-title: "{DB9444>}&lAnniversary Submission{<AEDB44}"
    gui-border: "DIAMOND_HOE:15" # ITEM_ID:CUSTOM_MODEL_DATA
    gui-board: "ACACIA_HANGING_SIGN:0"

    required-permission-to-submit: 'group.tofu'

  pekoSubmission:

    point-name: ""

    gui-title: ""
    gui-border: ""
    gui-board: ""

    required-permissions-to-submit: ''